### ISSUE TITLE
Sandhi-Samasa split for longer text

### ISSUE THREAD

**Issue by hrishikeshrt** [hrishikeshrt/vaiyyakarana#2]
Pointed out by @vipranarayan14
Currently, longer length is not split correctly (due to the limit of 128 characters present in SSCS).

Use folding/unfolding of input to support larger text.

**Comment by vipranarayan14** [comment]
That's a good idea.

**Comment by vipranarayan14** [comment]
@hrishikeshrt Thanks! Is it deployed? Can I try it now in the telegram app?

**Comment by hrishikeshrt** [comment]
You may try in the App, yes. If there are any issues, please let me know.
I am in the process of cleaning up code and making it more structured as well, so active testing would actually help a lot.

**Comment by vipranarayan14** [comment]
Tried a whole sloka with two long compounds. Works perfectly! Thanks!

Input:
```
यस्यावस्कन्दलीलावलितबलपरिस्पन्दखर्वीकृतोर्वीसंरम्भोत्तम्भनायोन्नमितभरनमत्कन्धरासंधिरासीत्। 
शेषो विस्फारफुल्लस्फुटपृथुलफणाफूत्कृताग्निस्फुलिङ्गस्फूर्जत्संदोहसंदेहितविकटशिखामण्डलीरत्नखण्डः॥
```

Output:

```
यस्य-अवस्कन्द-लीला-वलित-बल-परिस्पन्द-खर्वीकृत-उर्वी-संरम्भ-उत्तम्भनाय-उन्नमित-भर-नमत्-कन्धरा-संधिः-आसीत्। 
शेषः-विस्फार-फुल्ल-स्फुट-पृथुल-फणा-फूत्कृत-अग्नि-स्फुलिङ्ग-स्फूर्जत्-संदोह-संदेहित-विकट-शिखा-मण्डली-रत्न-खण्डः॥
```
